### ISSUE TITLE
Does the actor network using the average of current Q(s,a)

### ISSUE THREAD

**Issue by lknownothing** [watchernyu/REDQ#1] opened 2021-03-14 07:39 UTC
when I  reproduce the algorithm. When I used average-Q in Actor, the algorithm will not convergence. 

and the reward will down. Can you tell me abount the `Actor_update` detail.

**Comment by watchernyu** [comment] 2021-03-15 14:26
@lknownothing Thanks for posting the issue! When we compute the policy loss (actor loss), we get the Q value from each Q network, we take the average of these Q values (for each data point, average over all Q networks), and then the policy loss is simply (alpha*log_prob - average_q).mean(), where the first term is the SAC entropy term, and the second term is the average of Q values. 

Hope that helps! We will soon release our codebase so hopefully, that will make things more clear.

**Comment by watchernyu** [comment] 2021-03-23 14:49
@lknownothing We just released REDQ source code! Maybe that will help clarify things, we will also soon post the tutorial. Hope that helps!

**Comment by lknownothing** [comment] 2021-03-24 02:49
> @lknownothing We just released REDQ source code! Maybe that will help clarify things, we will also soon post the tutorial. Hope that helps!

Thank you for your patience and kindness. It's  useful for me.

 Respectfully and sincerely,

**Comment by watchernyu** [comment] 2021-07-06 09:23
Since it seems the problem is solved, I will close this issue now, thanks!

**Closed as completed by watchernyu** 2021-07-06 09:23 UTC

**Comment by whalewang410** [comment] 2023-11-12 12:43
Hello，there is a question confusing me. why do you choose to use the  average Q to update the policy instead of the original way in SAC. For instance, you can choose the minimal Q value from subsets of the esemble Q sets.  Could you provide me with some reasons?

**Comment by watchernyu** [comment] 2023-11-12 17:08
@whalewang410 thanks for the question, you can totally just use the min, there is no significant performance difference. I vaguely recall we used average to make the theoretical part simpler. But in practice it does not make a difference. Hope that helps!

**Comment by whalewang410** [comment] 2023-11-13 07:38
Thank you for your answer !

**Comment by whalewang410** [comment] 2023-11-13 07:38
> @whalewang410 thanks for the question, you can totally just use the min, there is no significant performance difference. I vaguely recall we used average to make the theoretical part simpler. But in practice it does not make a difference. Hope that helps!

thanks !
